import type { Metadata } from "next";

export const siteConfig: Metadata = {
  title: "Adarsh Singh | Senior Shopify Plus Engineer & AI Automation Developer",
  description:
    "Senior Software Engineer with 6+ years delivering enterprise-grade ecommerce, AI automation, cloud applications, and digital transformation solutions. Specialized in Shopify Plus, React, Next.js, AI Agents, Agentic Workflows, RAG Systems, and Enterprise Integrations. Building AI-powered Digital Commerce Solutions for Deloitte, EY, KPMG, McKinsey-level clients.",
  keywords: [
    "adarsh singh",
    "senior shopify plus engineer",
    "frontend architect",
    "ai automation developer",
    "digital transformation",
    "ai automation",
    "agentic ai",
    "generative ai",
    "large language models",
    "llm integration",
    "prompt engineering",
    "cloud architecture",
    "enterprise applications",
    "shopify plus",
    "headless commerce",
    "frontend architecture",
    "technical leadership",
    "stakeholder management",
    "solution design",
    "system integration",
    "api development",
    "reactjs",
    "nextjs",
    "typescript",
    "ai agents",
    "agentic workflows",
    "rag systems",
    "react",
    "tailwindcss",
    "framer-motion",
    "threejs",
    "space-portfolio",
    "agile",
    "devops",
    "ci/cd",
    "performance optimization",
    "cyber security",
    "data analytics",
    "business automation",
    "workflow automation",
    "enterprise solutions",
    "mern stack",
    "full stack developer",
    "software engineer",
    "portfolio",
  ] as Array<string>,
  authors: {
    name: "Adarsh Singh",
    url: "https://github.com/adarsh22-dev",
  },
} as const;
